# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  menu:
    main:
      - name: About me / Imprint
        url: /
        weight: 10
      - name: Articles
        url: blog/
        weight: 12
      - name: Videos
        url: videos/
        weight: 13
      - name: Stories
        url: stories/
        weight: 14
      - name: Projects
        url: projects/
        weight: 20
      - name: Experience
        url: experience/
        weight: 30


  
# Uncomment the lines below to configure your website in a second language.
de:
  languageCode: de
  contentDir: content/de
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
